module.exports = {
  aprobacion: require('./controllers/aprobacion'),
  cita: require('./controllers/cita'),
  cotizacion: require('./controllers/cotizacion'),
  trabajo: require('./controllers/trabajo'),
  orden: require('./controllers/ordenes'),
  login: require('./controllers/login'),
  example: require('./controllers/example'),
  reporte: require('./controllers/reporte'),
  osur: require('./controllers/osur'),
  taller: require('./controllers/taller'),
  ordenAnticipo: require('./controllers/ordenAnticipo'),
  dashboard: require('./controllers/dashboard'),
  administracion: require('./controllers/administracion'),
  mobile: require('./controllers/app.controller'),
  busquedaUnidad: require('./controllers/busquedaUnidad'),
  ordenServicio: require('./controllers/ordenServicio'),
  configurador: require('./controllers/configurador'),
  detalle: require('./controllers/detalle'),
  cobrar: require('./controllers/cobrar/cobrar'),
  dashboardCallcenter: require('./controllers/dashboardCallcenter'),
  commonFunctions: require('./controllers/commonFunctions') //LQMA 11062017
}
